version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./Retail_ML_pipeline/storage:/storage
  backend:
    build: backend
    ports:
      - 8090:8090
    volumes:
      - ./Retail_ML_pipeline/storage:/storage
